### ISSUE TITLE
ERROR: yaml.scanner.ScannerError

### ISSUE THREAD

**Issue by x1184** [WangQiru/docker-aria2-with-ariang#2]
docker-compose up -d
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 384, column 27

**Comment by HenryQW** [comment]
Looks like an invalid syntax in your compose file, mind posting it here?

**Comment by x1184** [comment]
I modified the syntax error and encountered a new problem.

[root@~] docker-compose --version
docker-compose version 1.13.0, build 1719ceb
[root@ ~] docker-compose up -d


**ERROR: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.13.0 or greater.**


[root@~] docker -v
Docker version 1.7.1, build 786b29d/1.7.1

How can I solve it? , My current server system is CentOS6

**Comment by HenryQW** [comment]
I'm not a CentOS user. Under Debian I usually do:

```sh
apt update && apt install --only-upgrade docker-ce -y
```

Your docker version is way out-dated.

![image](https://user-images.githubusercontent.com/5896343/47453958-da8cf480-d7c5-11e8-9872-012f8c443437.png)


Refer to this maybe: https://docs.docker.com/install/linux/docker-ce/centos/#install-docker-ce

**Comment by x1184** [comment]
Many thanks to u, i have solved this problem by myself 👍  .
It is indeed necessary to update the version.
